### ISSUE TITLE
Do you participate in mentoring or coaching others?

### ISSUE THREAD

**Issue by jedireza** [dragonmantank/ama#5]

**Comment by dragonmantank** [comment]
Not really, and I'm going to use the old excuse of that I don't have time. I do try and help out people with questions in #phpmentoring on freenode, questions on my blog, and in person at conferences, but I don't have any long standing mentoring setups.

I do teach though, through the php[architect] training courses, a few different classes like the basic PHP course, a Drupal 7 development course, and a Drupal 8 quick start. Those are paid gigs though. I also love to talk at conferences, but there's a big difference between giving someone advice and being a mentor in the traditional sense. So I do it in little chunks.
