### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by tenhobi** [dragonmantank/ama#6]

**Comment by dragonmantank** [comment]
I've looked at it once or twice, but I've never done anything with it. There didn't seem to be anything that jumped out at me as any better than what Angular provides, or that you could cobble together with some JS and Handlebars. 

I don't do many huge single page applications either, so I may just not have had a good use case for needing Polymer.

**Comment by tenhobi** [comment]
:+1: 

I think Polymer is really good if you want to use the ability of custom elements or if you do not want to write redundant code.

Instead of a lot of divs and classes you just wrote something like this bellow + create the simple reusable elements.

``` html
<nav-bar>
  <nav-item>Alfa</nav-item>
  <nav-item icon="flash">This is beta</nav-item>
  <nav-item unicorn>This item will have unicorn power!</nav-item>
</nav-bar>
```

That is what I like. :smile_cat:
